const categories = [
  { id: "FOREIGN", name: "외국어" },
  { id: "ART", name: "미술/공예" },
  { id: "DESIGN", name: "디자인" },
  { id: "MUSIC", name: "음악" },
  { id: "SHOW", name: "연기/마술" },
  { id: "DANCE", name: "댄스" },
  { id: "PHOTO", name: "사진/영상" },
  { id: "HABIT", name: "취미 생활" },
  { id: "INVEST", name: "투자/부업" },
  { id: "SPORTS", name: "스포츠" },
  { id: "HEALTH", name: "건강" },
  { id: "CAREER", name: "커리어" },
  { id: "EXAM", name: "시험/자격증" },
  { id: "FASHION", name: "패션/뷰티" },
  { id: "COOK", name: "요리/ 조리" },
  { id: "PET", name: "펫/반려동물" },
  { id: "INTERIOR", name: "홈리빙 / 인테리어" },
  { id: "RELRATIONSHIP", name: "인간관계" },
  { id: "TRAVEL", name: "여행" },
  { id: "LIFE", name: "라이프" },
  { id: "SCHOLARSHIP", name: "학문" },
  { id: "PROGRAMMING", name: "프로그래밍" },
  { id: "ENTREPRENEUR", name: "창업" },
  { id: "ETC", name: "기타" },
];

export default categories;
